### ISSUE TITLE
Import map isn't updated sometimes unless retried 

### ISSUE THREAD

**Issue by anasanzari** [single-spa/import-map-deployer#106]
Storage: Google Cloud
PATCH requests return 200, but map isn't actually updated
However it works after retrying

**Comment by joeldenning** [comment]
Are you sure this isn't related to cache control or CDN edge location caching within GCP?

**Comment by anasanzari** [comment]
@joeldenning yes, i observed it a couple of times and verified it. As a workaround, i'm doing the PATCH request 3 times and it seems to fix the issue.

**Comment by joeldenning** [comment]
This one will be difficult to track down without a way for me to reproduce it. I have a GCP import-map-deployer running at https://github.com/joeldenning/live-import-map-deployer, with CI processes calling the import map deployer in ~20 repos. But I haven't seen this problem before. Any ideas on how I can reproduce it?

**Comment by anasanzari** [comment]
@joeldenning I couldn't find a way to reproduce it with consistency. I'm not facing the issue after retrying is added. Thanks for the support.
