### ISSUE TITLE
Understanding http auth for getting json

### ISSUE THREAD

**Issue by rperrotebee** [single-spa/import-map-deployer#108]
Hi,

I am trying to use the deployer to avoid cache problems in my microfronts.

I require to update the import-map.json there is some kind of security like username and password, but when I want to fetch it from my container (index.html) I don't want to use the http auth.

is there any configuration for the import-map-deployer to act this way?

**Comment by rperrotebee** [comment]
now I understand the use of import-map-deployer

**Comment by joeldenning** [comment]
Yes generally we don't recommend using import-map-deployer to host the production import map, since it can be a security risk to expose the service to the public. Instead, host the file on a CDN and have import-map-deployer update it.
