### ISSUE TITLE
npx command not working on Node 12.x

### ISSUE THREAD

**Issue by brenoalvs** [single-spa/import-map-deployer#116]
Hey, it's my first time using this. Very nice tooling!

I didn't find which Node version is supported in the documentation so I'm just reporting it.
It's working fine on Node.js 14.x for me.

```sh
$ npx import-map-deployer config.js
Cannot find module 'fs/promises'
Require stack:
- ~/.npm/_npx/27925/lib/node_modules/import-map-deployer/src/io-methods/filesystem.js
- ~/.npm/_npx/27925/lib/node_modules/import-map-deployer/src/io-methods/default.js
- ~/.npm/_npx/27925/lib/node_modules/import-map-deployer/src/io-operations.js
- ~/.npm/_npx/27925/lib/node_modules/import-map-deployer/src/web-server.js
- ~/.npm/_npx/27925/lib/node_modules/import-map-deployer/bin/import-map-deployer
```

Thanks!

**Comment by joeldenning** [comment]
import-map-deployer requires nodejs@>=14. See code below that shows this:

https://github.com/single-spa/import-map-deployer/blob/dd2a6c0f3fae49f3d0021d76583e7af4be7d826f/package.json#L26-L28
