### ISSUE TITLE
Add ability to specify which import map to patch

### ISSUE THREAD

**Issue by bhovhannes** [single-spa/import-map-deployer#148]
Hello,
we are happy users of `import-map-deployer`. We have it configured to update an import map hosted in S3 bucket. Url is like `s3://<something>/prod/import-map.json`.

We are going to have a brand new product with its own import map. However duplicating all our AWS infrastructure for the new product seems to be an overkill. Instead, we'd like to make `import-map-deployer` to be able to update `s3://<something>/prod/{productName}/import-map.json` where `productName` we will send as in a request body for `PATCH/import-map.json` endpoint.

Is there any reason `import-map-deployer` does not currently allow to specify import map to update during PATCH operation?

I am ready to open a pull request implementing that feature, but first wanted to make sure it conforms to the vision of this project.

Thanks!

CC @joeldenning @TheMcMurder

**Comment by TheMcMurder** [comment]
Knowing what I know about the Adobe Workfront infrastructure why doesn't using the env flag work for you? 

Did y'all change the implementation in a way that makes it so you can't use that flag to change a specific import map?

**Comment by bhovhannes** [comment]
Env flag will work, but it will require making changes in import-map-deployer config for each new product.

To be honest I discovered that flag after opening this issue. Making change for each new product is an acceptable tradeoff.

However, ability to specify import map during PATCH request will allow to make everything dynamic and that way we will not hardcode names of import maps. I wonder why import-map-deployer was not built that way and requires to list all import maps you work with in its config.

**Comment by bhovhannes** [comment]
Thank makes sense. Thanks!
