### ISSUE TITLE
How to use the Docker Hub image to push to Kubernetes cluster

### ISSUE THREAD

**Issue by kristianmandrup** [single-spa/import-map-deployer#28]
I'm following along your importmaps-deployer video tutorial.

I see there is a [live-import-map-deployer](https://github.com/joeldenning/live-import-map-deployer)

This is example of extending the `import-map-deployer` from docker hub

```
FROM canopytax/import-map-deployer
```

Wondering about the `conf.js` file. I've seen it in the video as `config.json` I believe? Please add sth to the readme for `live-import-map-deployer` and update it to match the latest `single-spa/import-map-deployer` image and conventions

Took me a while to figure all this out.

What about using the `gcloud` CLI to push the image and interact with the cluster?

Thanks for everything. Very excited to get this infrastructure all working :)

**Comment by joeldenning** [comment]
I saw and commented on your PR in https://github.com/joeldenning/live-import-map-deployer/pull/1

Yes it should switch over to `singlespa/import-map-deployer`.

The filename for the config doesn't matter, as long as you provide it as an argument to `yarn start`. I did so in live-import-map-deployer [here](https://github.com/joeldenning/live-import-map-deployer/blob/91f06dee2054f9c4e1c35ccb518864c257fe535f/Dockerfile#L7)

> What about using the gcloud CLI to push the image and interact with the cluster?

Whatever you'd prefer working with - import-map-deployer is just the image. It's up to you to run the container and set up CI for it however you'd like.
