### ISSUE TITLE
Add support for "packages via trailing slashes"

### ISSUE THREAD

**Issue by joeldenning** [single-spa/import-map-deployer#37]
See https://github.com/WICG/import-maps/#packages-via-trailing-slashes. This could be useful for those wanting to take things to the next level with in-browser modules, and allow for multiple entry points to a module.

Additionally it would be important for jspm@3 single-spa applications, where they patch the import map with an auto-generated one from jspm that would include trailing slashes.

**Comment by BartJanvanAssen** [comment]
Not sure if I fully understand the additional jspm case, I think it should work with this pr. If not I would need bit more detail on that one :)

**Comment by joeldenning** [comment]
jspm@3 isn't used heavily by the single-spa community right now, but it generates an import map that includes packages with trailing slashes. Users then would call PATCH /import-map.json with that import map, and expect it to work.

**Comment by joeldenning** [comment]
This is released in https://github.com/single-spa/import-map-deployer/releases/tag/v2.2.0

**Comment by joeldenning** [comment]
Thanks @BartJanvanAssen
