### ISSUE TITLE
Add support for import map scopes

### ISSUE THREAD

**Issue by joeldenning** [single-spa/import-map-deployer#38]
Not sure exactly what this would look like. Perhaps the best way to support this would be through `PATCH /import-map.json`?

**Comment by victorlevasseur** [comment]
Hi, that's exactly the feature I'm looking for. I intend to manage the scopes via a PATCH request to /import-map.json.

**Comment by joeldenning** [comment]
Do you have interest in submitting a PR for this? If not, perhaps I would get to it at some point. I think the thing to think about with an implementation is that it would be nice to verify that all the URLs in the import map scopes are valid/reachable URLs. In the code we do this with https://github.com/single-spa/import-map-deployer/blob/master/src/verify-valid-url.js.

Another thing to consider with that is that I believe that relative URLs (`./)` inside of scopes are resolved relative to the page's base URL - not relative to the scope's URL. I say this based on https://wicg.github.io/import-maps/#sort-and-normalize-scopes. So we'd need to take that into account when calculating the URL to check for reachability

**Comment by joeldenning** [comment]
Support for this is now merged and available on Dockerhub. Thanks @BartJanvanAssen for your work on this.
