### ISSUE TITLE
Allow adding/updating service with non-public url

### ISSUE THREAD

**Issue by jsoriao** [single-spa/import-map-deployer#41]
When I run a curl command to a running instance of import-map-deployer

    curl -d '{"service":"service-name", "url":"service-url"}' -X PATCH localhost:5000/services\?env=dev ...

, it first verifies that the file in `service-url` exists by making a network request. However, if the `service-url` is not public, it fails.

It might be preferable if this check/verification can be disabled optionally, to allow adding service urls which are secured in some cloud storage.

**Comment by joeldenning** [comment]
I fixed this in #43 - it's now on dockerhub. If you want to use it via npm let me know and I can publish a new version
