### ISSUE TITLE
I'd like to volunteer to convert this package to TypeScript

### ISSUE THREAD

**Issue by dgreene1** [single-spa/import-map-deployer#45]
## Why would I want to do this?

Because I ultimately plan on forking this application so that I can make customizations but still occasionally merge new changes from the upstream source back into my private fork. But since my fork will be in TypeScript, it would be much easier for me to do that upstream merge if both are in TypeScript.

## But why TypeScript?

* it would help maintainers who are accepting PRs since you get that nice warm fuzzy feeling that if they were able to get past the husky hook that runs the compiler then the PR must be mergeable. We could also rely on Github Actions to run the typescript type checker/compiler as a PR merge gate.
* I'd be using the conversion as an excuse to better understand how this library works.
* People like me are much more willing to help maintain a library if the library is in TypeScript.

**Comment by frehner** [comment]
I'd be open to adding JSDoc type definitions and outputting a `.d.ts` file as part of the build of this project. Much like the work that was done in [single-spa layout](https://github.com/single-spa/single-spa-layout/blob/master/src/constructApplications.js)

I'm not sure I like the idea of converting the whole project to TS though. People who don't like or use typescript are much less likely to help maintain a library if it's in TS - it's a huge barrier to them.

Just my 2 cents, but I'm willing to be overridden if other maintainers chime in and are ok with it.

**Comment by joeldenning** [comment]
I think reviving the tests is a more important concern right now than adding types. Right now we don't have any working tests. I worked on this in https://github.com/single-spa/import-map-deployer/pull/20 but never completed it.

**Comment by dgreene1** [comment]
As recently as 2019 surveys showed that 65.3% of developers have tried Typescript and that if those who have tried it 88.9% would use it again.

https://2019.stateofjs.com/javascript-flavors/

Let me put it this way, I’d be open to becoming an official maintainer of this repo and I would add tests as well, but only if it’s in TypeScript. I just don’t have time to write the number of quality automated tests that static analysis gives me for free. It’s not that I’m a hard-liner about other people’s language choices, but with my time availability I can only afford to spend time on projects that allow me to be highly efficient at development and with code reviews.

Statistics aside, I respect that the primary maintainer has to make the choice based on their preferences. So if @joeldenning doesn't want TS, then that’s cool.

**Comment by joeldenning** [comment]
Anthony and I discussed this over DM - we appreciate your desire to help, but don't think we'd like to have you switch it over to typescript. I love seeing new contributors, but am uncomfortable accepting conditions/demands for a contributor to volunteer their time.

The following tweet comes to mind: https://twitter.com/_developit/status/1251176832424181762?lang=en.

In my opinion, a person looking to enact change in a project should first seek to fit into the existing project and make themselves useful with pull requests. After the maintainers recognize the same contributor sending in pull requests, they generally will grant write access and start including them in more things related to the project. Once a relationship and trust have been established, the contributor's proposal to make big changes (such as changing programming languages) could be a healthy discussion amongst maintainers.

Had you followed a path similar to that ^, Anthony and I would likely be more receptive to your proposal.

**Comment by dgreene1** [comment]
Yea @joeldenning i agree. This is a great learning opportunity for me. It’s also a pretty humiliating moment. Any chance we can delete this issue?

I will say I’ve been an active member of the community and popular evangelist within multiple companies. You just might know it because I often write under a pseudonym on Twitter and dev.to.

But seriously, I regret the way I approached this and I would love to make it go away. If you’re not cool with that, I’m okay with having my shame live on forever in the internet way back machine. 😭

**Comment by frehner** [comment]
if you're uncomfortable with this being public, I'm ok with it being deleted. our intention wasn't to shame or anything like that.

and we really do appreciate the offer to help! like Joel mentioned earlier, if we see a history of a person contributing, we often feel good about leaving bigger decisions like this to them - they've earned our trust :)

would love to still work out a way that would allow you to feel comfortable and productive in contributing

**Comment by dgreene1** [comment]
Yea @joeldenning i agree. This is a great learning opportunity for me. It’s also a pretty humiliating moment. Any chance we can delete this issue?

I will say I’ve been an active member of the community and popular evangelist within multiple companies.

But seriously, I regret the way I approached this and I would love to make it go away. If you’re not okay with deleting the issue, I guess I’ll live with having my shame persist forever in the internet way back machine. 😭

**Comment by joeldenning** [comment]
No worries, I don't have anything against you and am happy to continue working with you going forward. I recognize your profile picture from previous interactions (Github, maybe slack too?) and remember our previous interactions to have been positive.

I don't know how to delete Github issues, but don't have any problems doing so if it's possible.

**Comment by joeldenning** [comment]
Figured out how to delete the issue - doing that now.
