### ISSUE TITLE
Feature Request: Set S3 ACL other than public-read

### ISSUE THREAD

**Issue by zleight1** [single-spa/import-map-deployer#48]
We have a setup where setting the ACL of the import-map.json in S3 needs to be something other than public-read.

Right now in the s3 code, the PUT call is defaulted to 'public-read' and can't be overridden.

I think the best way would be another configuration variable, that validates against the list of pre-canned ACLs here: https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl

I'll open a PR for this, let me know if there is anything to know or watch out for.

**Comment by zleight1** [comment]
I also pushed an image to test it out, as can be found here: https://hub.docker.com/repository/docker/zleight1/import-map-deployer

**Comment by joeldenning** [comment]
Hi @zleight1 - sure I'm open to this. Let's make it an option within the config file? Perhaps something like this?

```js
// conf.js
module.exports = {
  "locations": {
    "prod": "s3://cdn.canopytax.com/import-map.json"
  },
  "s3": {
    "putObject": {
      "ACL": "public-read|something-else"
    }
  }
}
```

^ This sets us up to allow for changing any of the params passed to to s3's putObject function. I'm not sure if this would ever need to be different on a per-location basis?? If so, then maybe something like this?


```js
// conf.js
module.exports = {
  "locations": {
    "prod": {
      "url": "s3://cdn.canopytax.com/import-map.json",
      "s3": {
        "putObject": {
          "ACL": "public-read|something-else"
        }
      }
    }
  }
}
```

Thanks for offering to send in the PR - much appreciated.

**Comment by zleight1** [comment]
See updated PR
