### ISSUE TITLE
Add cache control header to import maps in Microsoft Azure

### ISSUE THREAD

**Issue by joeldenning** [single-spa/import-map-deployer#50]
Currently S3, Digital Ocean, and Google Cloud Storage all are instructed to send a Cache-Control HTTP response header when serving the import map file.

References:

https://github.com/single-spa/import-map-deployer/blob/6ff73eb1425ca5259fe3aa03fb779d6512d33757/src/io-methods/google-cloud-storage.js#L36

https://github.com/single-spa/import-map-deployer/blob/6ff73eb1425ca5259fe3aa03fb779d6512d33757/src/io-methods/s3.js#L61

However, the same thing does not exist for Microsoft Azure. We should add this to the Azure integration. The file to modify is https://github.com/single-spa/import-map-deployer/blob/master/src/io-methods/azure.js

**Comment by joeldenning** [comment]
Resolved in #52

**Comment by mellis481** [comment]
Based off the above, it appears that the IMD will automatically set a cache-control header to `CacheControl: "public, must-revalidate, max-age=0"` for the importmap.json file when it initially creates the file in the cloud.  This header is not correct, however, or it's at least not what I would want mine to be.

[Here](https://single-spa.slack.com/archives/C8R6U7MT7/p1605036214185300) is a discussion on the topic, but at a high level, the `public, must-revalidate, max-age=0` cache control header will only prevent _browser_ caching.  If you're using a cloud storage service like S3 with CloudFront, this file will still be cached at edge locations even after the file on the origin has been updated.  It's imperative that you see importmap.json files immediately.  You'll see in the discussion linked above, `no-cache` or `no-store` will avoid _any_ caching of the importmap.json file (even on edge locations) is what is truly desired.

If this is the case, the ideal behavior may be to use `no-cache` or `no-store` by default, OR allow IMD consumers to override it.  Let me know your thoughts.

**Comment by joeldenning** [comment]
Most CDNs will cache the import map at edge locations only for a short time when they see the max-age header. Caching the import map a little bit can be good for performance. Cloudfront, for example, sometimes will cache it in edge locations but it only lasts for a minute or so.

I'm open to adding no-cache or no-store to the headers, but I also think we might need to add a configuration option allowing people to change the max-age to be higher, since that's more responsible from a performance standpoint.

**Comment by dgreene1** [comment]
I agree with @joeldenning's solution (a configuration option and a possible reconsidering of the default) and I agree with @mellis481's assessment of the importance of this change.

All around 👍. So @joeldenning how would you like to approach this? Should this issue get reopened and then @mellis481 or I can make the PR?

**Comment by joeldenning** [comment]
Yes I'm open to a change allowing for configuring of the cache control header. I'd prefer a new Github issue, since this issue was already resolved and the new discussion is something different. I'm happy to review a pull request with the change.
