### ISSUE TITLE
Add correct Mime Type to S3, DO Spaces, Azure, and GCP Storage

### ISSUE THREAD

**Issue by joeldenning** [single-spa/import-map-deployer#51]
According to the import maps spec, import maps are required to send the mime type `application/importmap+json` in their response headers. SystemJS does not enforce this, but Chrome's native implementation does. We should update our io-methods so that AWS, Digital Ocean, Microsoft Azure, and GCP Storage are all instructed to do so whenever we modify the import map.

More info at https://github.com/WICG/import-maps#installation

**Comment by BartJanvanAssen** [comment]
i'll take it in on #52

**Comment by joeldenning** [comment]
Resolved in #52
