### ISSUE TITLE
Cant delete a service name with /

### ISSUE THREAD

**Issue by pguerrero-divilo** [single-spa/import-map-deployer#62]
I patch a service via http call to import-map-deployer API endpoint with a name that contains a slash in it's name like _@divilo/authentication_

I think import map deployer should validate service name before adding it's reference. Otherwise delete mehhod wont do

```
{
  "imports": {
    "single-spa": "https://cdn.jsdelivr.net/npm/single-spa@5.3.4/lib/system/single-spa.min.js",
    "vue": "https://cdn.jsdelivr.net/npm/vue@2.6.11/dist/vue.min.js",
    "vue-router": "https://cdn.jsdelivr.net/npm/vue-router@3.1.5/dist/vue-router.min.js",
    "@divilo/authentication": "https://assets.divilodemo.com/authentication/cef4e230dde1d946135647428ef4a65e/divilo-authentication.js"
  }
}
```

![image](https://user-images.githubusercontent.com/65544031/86806826-8b5e2480-c079-11ea-863b-685f1dd060e6.png)

**Comment by joeldenning** [comment]
Hmm this sounds like a bug in import-map-deployer. I'll try it out locally and see if there is a way we can allow for the DELETE to work.

**Comment by BartJanvanAssen** [comment]
Encountered this also. also encoding with %2F doesn't seem to work :(

**Comment by pguerrero-divilo** [comment]
Maybe we can upgrade delete method in order to receive body payload so you can choose how to delete via /:id (parameter) or by json body.

What do you think? @joeldenning and @BartJanvanAssen

**Comment by joeldenning** [comment]
This is not a bug, since the endpoint works correctly if you properly URL encode the service name in the URL.

<img width="928" alt="image" src="https://user-images.githubusercontent.com/5524384/87334145-7232f900-c4fb-11ea-8579-df0759d2cff7.png">

**Comment by pguerrero-divilo** [comment]
@joeldenning It will be a great idea to add this specification in README. Thanks Joel

**Comment by joeldenning** [comment]
Would you like to add this to the documentation? Something in the `PATCH /services` and `DELETE services` that says "Service names should be URL encoded."

**Comment by pguerrero-divilo** [comment]
@joeldenning Hi joel, sorry for answering so late. Sure, I'll prepare a PR with this update ;) thanks so much for your work and also single-spa team.
