### ISSUE TITLE
Should DELETE delete both entries - with and without trailing slash?

### ISSUE THREAD

**Issue by andygauntnervertex** [single-spa/import-map-deployer#64]
Afer reading it, I'm not sure if this is a duplicate of https://github.com/single-spa/import-map-deployer/issues/62 or not.  My apologies if it is.

1.  With `packagesViaTrailingSlashes=true`:

Calling `PATCH http://server:5000/services`
with this body:
```
{
    "service": "TestService",
    "url": "https://apis.google.com/js/client.js"
}
```

Adds two entries to the import map:
```
{
    "imports": {
        "TestService": "https://apis.google.com/js/client.js",
        "TestService/": "https://apis.google.com/js/"
    }
}
```

Great.

2.  **My question**:  When you call `DELETE http://server:5000/services/TestService`, it only removes one entry, and the import map now looks like:
```
{
    "imports": {
        "TestService/": "https://apis.google.com/js/"
    }
}
```

**Should it delete "TestService/" as well?**    I tried making a separate DELETE call -- calling various combinations:  `DELETE server:5000/services/TestService&#47;` , etc.

**Comment by joeldenning** [comment]
> Should it delete "TestService/" as well?

Yes, it should. I have submitted #65 to fix this.

**Comment by joeldenning** [comment]
Fix released in https://github.com/single-spa/import-map-deployer/releases/tag/v2.2.2

**Comment by dgreene1** [comment]
Thank you so much @joeldenning on behalf of my team. :)
