### ISSUE TITLE
Auth environment variables have no effect

### ISSUE THREAD

**Issue by kgehmlich** [single-spa/import-map-deployer#70]
Setting `HTTP_USERNAME` and `HTTP_PASSWORD` as in the Dockerfile example has no noticeable effect. They neither set nor override the username and password values for basic auth.

Have I misunderstood the point of these environment variables?

**Comment by joeldenning** [comment]
The `HTTP_USERNAME` and `HTTP_PASSWORD` environment variables are only used if your conf.js file says to use them. In the example in the readme, the conf.js file is copied into the final docker image, and it's presumed that the conf.js file references the environment variables as shown here:

See https://github.com/joeldenning/live-import-map-deployer/blob/de1b8994728f3d3b092f41c87d863dcc5ab6a2a7/conf.js#L2-L3

I see how this could be confusing, and am open to creating default environment variables for import-map-deployer

**Comment by kgehmlich** [comment]
@joeldenning yep, I totally missed that `conf.js` is what's using those variables. Makes total sense, I must have just glossed over that part.

I'd be happy to help out! My team is evaluating using IMD in our migration to MFE and we'd be happy to help improve the project.
