### ISSUE TITLE
IAM role support to prevent the need to rotate keys for S3

### ISSUE THREAD

**Issue by dgreene1** [single-spa/import-map-deployer#74]
**Enhancement Request**
A new configuration option would allow the import map deployer to run as a specific [IAM Role (cli ref provided here)](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html)  which would allow us to avoid using AWS CLI keys.

**Context / User Story:**

One of the AWS experts at my company @dsmith2828 pointed that due to our companies key rotating policies we would have to log into our EC2 instance every 3 months to update the AWS cli keys for the import map deployer

**Work Plan:**
I would write the PR and provide unit tests.

**Comment by joeldenning** [comment]
Hey @dgreene1, yes this should be supported. I thought though that this was done totally through AWS credential files, environment variables, and/or ec2 roles?

I'm looking at https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-iam.html and https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-shared.html and my impression is that the role is just assumed without any code changes? If I'm mistaken on this, I'm happy to review a pull request for this.

**Comment by dgreene1** [comment]
I’ll close this with the assumption that it works. If it doesn’t, I’ll reopen this issue. Thank you for finding those links. :)

**Comment by yzAlvin** [comment]
just leaving a comment for anyone else wondering the same thing:
I was able to get the import-map-deployer running in docker to work the the IAM role assigned to the ECS task, just have to make sure the role has a policy to allow access to the import map s3 buckets.

**Comment by ifedevops-kpmg** [comment]
@yzAlvin , were you able to confirm the access?

**Comment by glyhood** [comment]
@yzAlvin , were you able to confirm the access?

**Comment by yzAlvin** [comment]
@glyhood 
Yep
