### ISSUE TITLE
Noisy logging of health check requests

### ISSUE THREAD

**Issue by dijitali** [single-spa/import-map-deployer#81]
We use the `/health` endpoint as a Kubernetes readiness probe which results in a lot log noise because it gets called every few seconds.

Could we suppress logging of the `/health` endpoint if it returns a 200 response?

Happy to make a PR but looking for confirmation of:

- is the proposal OK?
- should I bother making it a configurable setting?
- if so, should it be off or on by default?

**Comment by joeldenning** [comment]
👍  sure, this sounds good to me.

> should I bother making it a configurable setting?

No, let's just always disable logging of the health endpoint.
