### ISSUE TITLE
Im getting cannot read importmap.json during health check

### ISSUE THREAD

**Issue by vongohren** [single-spa/import-map-deployer#92]
Right now Im getting this issue when building and deploying to cloud run.
I have solved it by adding USER root in my wrapping Dockerfile.

But it does not feel good, so I wonder what is suppose to be possible?

There is a line in this Dockerfile, that sets www to be owned by root, and I believe that conflicts with the user is set to node. That again conflicts with IO operation of reading the local importmap file.

So just curious to what is the right way of doing it?

**Comment by joeldenning** [comment]
Generally people haven't used the local file for deployed import maps, but prefer one of the other supported storage locations (like s3). When your configuration file is set to use s3, it shouldn't attempt to read the import map from local file.

With that said, I see the problem you described where root is the only thing with access to the www folder. This was added in https://github.com/single-spa/import-map-deployer/pull/78 and I'm not sure why it's that way. I'd be open to a pull request removing the chown.

**Comment by vongohren** [comment]
@joeldenning I have configured towards google cloud storage, so maybe there is something missing in the code base?

**Comment by joeldenning** [comment]
It looks like the code maybe uses the file system for the health check if their is no `location` in the config called `default`. Which isn't a good behavior. Perhaps a better behavior would be just to read the first manifest in the `locations` object if there's no location called `default`?

See this code:

https://github.com/single-spa/import-map-deployer/blob/841b26530c750b0725936747af037fcd3b0d9c0d/src/io-methods/default.js#L15-L23

https://github.com/single-spa/import-map-deployer/blob/841b26530c750b0725936747af037fcd3b0d9c0d/src/health-check.js#L5

Notice how the health check doesn't specify an `env` name as an argument when reading or writing to the manifest. Do you have interest in submitting a pull request to fix this?

**Comment by vongohren** [comment]
@joeldenning something like this? https://github.com/single-spa/import-map-deployer/pull/95
Btw, I dont know what im doing wrong with git here, since my old commits is not gone?
Is this some rebase thing or?

I merged origin master into my fork master. But it doesnt sync up?
Any suggestions to what I can do?

**Comment by joeldenning** [comment]
It's okay, the diff looks good and the commits will be squashed when they get merged. The reason is that you didn't branch off of master for the first PR, so now your master branch has commits that the upstream repo does. If you wish to contribute more in the future, you can run the following, and then branch off of master for future PRs.

```sh
git fetch origin
git reset --hard origin/master
```

**Comment by joeldenning** [comment]
Fix released in https://github.com/single-spa/import-map-deployer/releases/tag/v3.3.1
